logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.orientechnologies: INFO
    com.kerz: INFO    

orient:
  host: 192.168.99.100
  user: root
  password: s3cret
  db: test-graph-1
  
geocoder:
  clazz: com.kerz.geo.mapzen.MapzenGeocoder
  uri: https://search.mapzen.com/v1/search
  key: search-ND7BVJ
  country: USA
